
    workflows:
      shofe-rider:
        name: Shofe Rider Build
        instance_type: mac_mini_m1
        max_build_duration: 60
        environment:
          flutter: stable
        scripts:
          - name: Clean
            script: |
              flutter clean
              flutter pub get
        artifacts:
          - build/app/outputs/flutter-apk/*.apk
