workflows:
  shoferider-android:
    name: Shofe Rider Android Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.22.3
      cocoapods: default
      xcode: latest
    scripts:
      - name: VERIFY V2
        script: |
          echo "Checking AndroidManifest"
          cat android/app/src/main/AndroidManifest.xml | grep flutterEmbedding
      - name: Force Flutter 3.22.3
        script: |
          flutter --version
          flutter channel stable
          flutter upgrade
          flutter --version
      - name: NUKE V1 FILES
        script: |
          rm -f android/app/src/main/java/io/flutter/app/FlutterActivity.java
          rm -f android/app/src/main/kotlin/**/MainActivity.java
          rm -f android/app/src/main/kotlin/**/MainActivity.kt
          echo "V1 files deleted successfully"
      - name: Install Dependencies
        script: flutter pub get
      - name: Clean Android
        script: |
          cd android
          ./gradlew clean
          cd ..
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - shofer.zimconnect@gmail.com
  triggering:
    events:
      - push
    branch_patterns:
      - pattern: 'main'
        include: true
        source: true
