name: shofe_rider
description: Shofe Rider - ZimConnect ride hailing app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  # FIREBASE - WORKS WITH FLUTTER 3.24.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_firestore: ^4.13.6

  # STATE + NETWORK
  provider: ^6.1.2
  http: ^1.1.2

  # MAPS + LOCATION
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.1
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
