name: shofe_rider
description: Shofe Rider - ZimConnect ride hailing app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # FIREBASE - V4 COMPATIBLE WITH FLUTTER 3.24.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_firestore: ^4.13.6

  # OTHER PACKAGES
  provider: ^6.1.2
  http: ^1.1.2
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.3.1
  geolocator: ^10.0.0

flutter:
  uses-material-design: true
